export const buttonPad = [
  {
    btnId: "clear",
    btnOnPress: "clear",
    btnStyle: "light-gray",
    btnLabel: "C",
  },
  {
    btnId: "negative",
    btnOnPress: "negative",
    btnStyle: "light-gray",
    btnLabel: "+/-",
  },
  {
    btnId: "percentage",
    btnOnPress: "percentage",
    btnStyle: "light-gray",
    btnLabel: "%",
  },
  {
    btnId: "divide",
    btnOnPress: "/",
    btnStyle: "yellow",
    btnLabel: "/",
  },
  {
    btnId: "seven",
    btnOnPress: "7",
    btnStyle: "dark-gray",
    btnLabel: "7",
  },
  {
    btnId: "eight",
    btnOnPress: "8",
    btnStyle: "dark-gray",
    btnLabel: "8",
  },
  {
    btnId: "nine",
    btnOnPress: "9",
    btnStyle: "dark-gray",
    btnLabel: "9",
  },
  {
    btnId: "multiply",
    btnOnPress: "*",
    btnStyle: "yellow",
    btnLabel: "*",
  },
  {
    btnId: "four",
    btnOnPress: "4",
    btnStyle: "dark-gray",
    btnLabel: "4",
  },
  {
    btnId: "five",
    btnOnPress: "5",
    btnStyle: "dark-gray",
    btnLabel: "5",
  },
  {
    btnId: "six",
    btnOnPress: "6",
    btnStyle: "dark-gray",
    btnLabel: "6",
  },
  {
    btnId: "subtract",
    btnOnPress: "-",
    btnStyle: "yellow",
    btnLabel: "-",
  },
  {
    btnId: "one",
    btnOnPress: "1",
    btnStyle: "dark-gray",
    btnLabel: "1",
  },
  {
    btnId: "two",
    btnOnPress: "2",
    btnStyle: "dark-gray",
    btnLabel: "2",
  },
  {
    btnId: "three",
    btnOnPress: "3",
    btnStyle: "dark-gray",
    btnLabel: "3",
  },
  {
    btnId: "add",
    btnOnPress: "+",
    btnStyle: "yellow",
    btnLabel: "+",
  },
  {
    btnId: "zero",
    btnOnPress: "0",
    btnStyle: "dark-gray",
    btnLabel: "0",
  },
  {
    btnId: "decimal",
    btnOnPress: ".",
    btnStyle: "dark-gray",
    btnLabel: ".",
  },
  {
    btnId: "equals",
    btnOnPress: "=",
    btnStyle: "yellow",
    btnLabel: "=",
  },
];
